Repository hygoni/precise-leak-sanitizer, pull requests merged in 2024-02, with the labels that each got.

#35 Change STL to sanitizer common library
  compiler-rt/lib/plsan/plsan.cpp
  compiler-rt/lib/plsan/plsan.h
  compiler-rt/lib/plsan/plsan_handler.cpp
  compiler-rt/lib/plsan/plsan_handler.h
  compiler-rt/lib/plsan/plsan_shadow.cpp
Labels: hotfix

#37 36 plsan allocator
  clang/include/clang/Driver/SanitizerArgs.h
  compiler-rt/lib/plsan/CMakeLists.txt
  compiler-rt/lib/plsan/plsan.cpp
  compiler-rt/lib/plsan/plsan.h
  compiler-rt/lib/plsan/plsan_allocation_functions.cpp
  compiler-rt/lib/plsan/plsan_allocator.cpp
  compiler-rt/lib/plsan/plsan_allocator.h
  compiler-rt/lib/plsan/plsan_handler.cpp
  compiler-rt/lib/plsan/plsan_interceptors.cpp
  compiler-rt/lib/plsan/plsan_internal.h
  compiler-rt/lib/plsan/plsan_linux.cpp
  compiler-rt/lib/plsan/plsan_new_delete.cpp
  compiler-rt/lib/plsan/plsan_posix.cpp
  compiler-rt/lib/plsan/plsan_posix.h
  compiler-rt/lib/plsan/plsan_shadow.cpp
  compiler-rt/lib/plsan/plsan_shadow.h
  compiler-rt/lib/plsan/plsan_thread.cpp
  compiler-rt/lib/plsan/plsan_thread.h
  compiler-rt/lib/sanitizer_common/sanitizer_internal_defs.h
  llvm/include/llvm/Transforms/Instrumentation/PreciseLeakSanitizer.h
  llvm/lib/Transforms/Instrumentation/PreciseLeakSanitizer.cpp
Labels: enhancement

#41 19 fix testcases
  testcases/c/leak/memcpy_builtin-2.c
  testcases/c/leak/p1.c
  testcases/c/leak/p3.c
  testcases/c/leak/var_arr-2.c
  testcases/c/leak/wrapper-2.c
  testcases/c/leak/wrapper-4.c
  testcases/c/noleak/both-5.c
  testcases/c/noleak/memcpy-2.c
  testcases/c/noleak/memcpy-3.c
  testcases/c/noleak/memmove-3.c
  testcases/c/noleak/p2.c
Labels: bug

#40 Simplify handling local variables
  compiler-rt/lib/plsan/plsan.cpp
  compiler-rt/lib/plsan/plsan.h
  compiler-rt/lib/plsan/plsan_allocator.cpp
  compiler-rt/lib/plsan/plsan_thread.cpp
  llvm/include/llvm/Transforms/Instrumentation/PreciseLeakSanitizer.h
  llvm/lib/Transforms/Instrumentation/PreciseLeakSanitizer.cpp
Labels: enhancement

#46 Fix: remove new, delete keyword in plsan.cpp
  compiler-rt/lib/plsan/plsan.cpp
Labels: bug

#69 testcases: add __builtin_alloca() in non-entry basic blockc case
  testcases/c/functional/builtin_alloca/builtin_alloca.c
Labels: enhancement

#71 Optimization: memset_wrapper to builtin memset
  compiler-rt/lib/plsan/plsan.cpp
  compiler-rt/lib/plsan/plsan.h
  llvm/include/llvm/Transforms/Instrumentation/PreciseLeakSanitizer.h
  llvm/lib/Transforms/Instrumentation/PreciseLeakSanitizer.cpp
Labels: enhancement

#85 Hotfix: fix wrong argument instrumenting while handle builtin alloca
  llvm/lib/Transforms/Instrumentation/PreciseLeakSanitizer.cpp
Labels: bug

#86 Optimization: Do not read same metadata several times in same action
  compiler-rt/lib/plsan/plsan.cpp
  compiler-rt/lib/plsan/plsan.h
  compiler-rt/lib/plsan/plsan_allocator.cpp
  compiler-rt/lib/plsan/plsan_allocator.h
Labels: enhancement

#89 Fix unaligned pointer for secondary allocator
  compiler-rt/lib/plsan/plsan_allocator.cpp
Labels: bug
